ZaiusInc/zaius-magento-2

- composer.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/12)
> hotfix composer.json version.

- Observer/NewsletterSubscriberSaveObserver.php
It's validating if it has a value, and if not Zaius auto handle it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/14)
> [ZAIR-153] Subscribe > Check if there is timestamp

- Observer/NewsletterSubscriberSaveObserver.php
Checking the return and logging in case obtain a wrong timestamp.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/19)
> [ZAIR-153] Subscribe event > Add log

- Model/ProductRepository.php
Simple products include `parent_product_id` param with their own ID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/20)
> [ZAIR-144] API return > Simple products > Add parent product Id param

- Observer/OrderPlaceAfterObserver.php
- Observer/OrderSaveAfterObserver.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/21)
> Remove calls to getIsTrackingOrdersOnFrontend from observers.

- Model/Client.php
- Model/SchemaRepository.php
- etc/adminhtml/system.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/23)
> [ZAIR-141] Enabling Batch Request

- Observer/CustomerLoginObserver.php
- Observer/CustomerRegisterObserver.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/24)
> ZAIR-161 Customer Login and Register events should send identifiers

- Controller/Hook/Create.php
https://www.loom.com/share/dce4c96325fb4c0b942af9f32fae5a17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/32)
> [ZAIR-163] Hotfix >Updating shopping cart link

- README.md
- composer.json
- etc/module.xml
Revert composer.json changes that targeted development branches; officially update the version to 1.0.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/35)
> version bump 1.0.0 -> 1.0.1.

- composer.json
- etc/module.xml
- view/frontend/requirejs-config.js
- view/frontend/web/js/ads.js
- view/frontend/web/js/zaius.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/37)
> [ZAIR-168] Avoiding AdBlock extra load

- composer.json
- etc/module.xml
- view/frontend/requirejs-config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/38)
> [ZAIR-168] Hotfix > Updating 1.0.2 -> 1.0.3

- view/frontend/templates/snippet.phtml
- view/frontend/web/js/zaius.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/40)
> Getting JS with VUID included

- Helper/Sdk.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/41)
> ZAI-187 fix distinct view-level API keys

- Model/CustomerRepository.php
- Observer/CustomerAddressSaveObserver.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/43)
> ZAI-195 fix updated address sent to Zaius

- Model/Client.php
- Model/ProductScopeManager.php
- Model/TrackScopeManager.php
- Observer/ProductSaveObserver.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/47)
> ZAI-193 fix Backend Data Is Not Routing To The Correct Namespaces

- Model/ProductRepository.php
- Model/ProductScopeManager.php
- Model/TrackScopeManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/50)
> ZAI-192 Products with conflicting store_view configs

- Model/SchemaRepository.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/51)
> ZAI-187 add store view to order schema creation

- Model/CustomerRepository.php
- Model/OrderRepository.php
- Model/ProductRepository.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/52)
> ZAI-191 returning empty array when the tracking ID parameter is omitted

- Model/Client.php
- Observer/NewsletterSubscriberSaveObserver.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/53)
> ZAI-196 fix email attribute, tracking store

- Model/ProductRepository.php
- Model/ProductScopeManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/58)
> ZAI-191 fix multiple store view product

- Model/ProductScopeManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/60)
> ZAI-192 fix multi store view

- Model/ProductRepository.php
- Model/ProductScopeManager.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/61)
> ZAI-191 fix api results

- Model/ProductRepository.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/62)
> ZAI-192 fix product has no view variants

- Helper/Sdk.php
- Model/Client.php
- Model/Cron.php
- composer.json
- etc/config.xml
We will need to also increment the composer.json to specifically call out requiring 1.0.2 or above, once the new SDK release is verified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/64)
> ZAI-224 Disabled all queuing / batching functionality
